In [2]:
import numpy as np
import sys

#set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None)

In [3]:
np.set_printoptions(precision=4) #控制输出的小数点个数是4
arr = np.array([1.123456789])
print(arr)

np.set_printoptions(threshold=5) #控制输出的值的个数为6，其余以...代替
arr = np.arange(10)
print(arr)
np.set_printoptions(threshold=sys.maxsize) #控制台输出所有的值，不需要省略号
print(arr)

eps = np.finfo(float).eps
x = np.arange(4)
print(x**2 - (x + eps)**2)

np.set_printoptions(suppress=True)
print(x**2 - (x + eps)**2)

[1.1235]
[0 1 2 ... 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[-4.9304e-32 -4.4409e-16  0.0000e+00  0.0000e+00]
[-0. -0.  0.  0.]


precision：控制输出的小数点个数，默认是8
threshold：控制输出的值的个数，其余以…代替；
    当设置打印显示方式threshold=np.nan，（换成sys.maxsize）
    意思是输出数组的时候完全输出，不需要省略号将中间数据省略
suppress： 当suppress=True，表示小数不需要以科学计数法的形式输出

np.finfo(float).eps: float浮点数的最小正数的值

In [13]:
print(np.finfo(float).eps)

2.220446049250313e-16
