In [20]:
import numpy as np

In [ ]:
a = np.array([2,3,4])
print(a)
print(a.dtype)

b=np.array([(1,5,2,3),(4,5,6)])
print(b)

In [6]:
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
np.empty((2,3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

In [11]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b**2)
print(10 * np.sin(a))

print(a < 35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


## 矩阵运算


matlab中有.* ,./等等

但是在numpy中，如果使用+，-，×，/优先执行的是各个点之间的加减乘除法

如果两个矩阵（方阵）可既以元素之间对于运算，又能执行矩阵运算会优先执行元素之间的运算

In [15]:
A = np.arange(10,20)
B = np.arange(20,30)
print(A+B)
print(A*B)
print(A//B)
print(B/A)


[30 32 34 36 38 40 42 44 46 48]
[200 231 264 299 336 375 416 459 504 551]
[0 0 0 0 0 0 0 0 0 0]
[2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667
 1.625      1.58823529 1.55555556 1.52631579]


如果需要执行矩阵运算，一般就是矩阵的乘法运算

In [19]:
a = np.ones(4)
b = a * 2
a.reshape((2,2))
print(a)
print(a.reshape(2,2))
print(b)
np.dot(a,b)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[2. 2. 2. 2.]


8.0

## 一些常用的全局函数

In [22]:
b = np.arange(3)
print(b)

np.exp(b)
np.sqrt(b)

c = np.array([2,-1,4])
print(np.add(b,c))

[0 1 2]
[2 0 6]


## 矩阵的索引分片遍历

In [26]:
a = np.arange(10) ** 3
print(a)
print(a[2:5])
print(a[:6:2])
a[:6:2] = -1000
print(a[:6:2])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27 64]
[ 0  8 64]
[-1000 -1000 -1000]


In [37]:
b = np.arange(16).reshape(4,4)
print(b)

for row in b:
    print(row)

for node in b.flat:
    print(node)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [43]:
print(b.ravel())
b.resize(2,8)
print(b)

c = b.astype(float)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]


In [47]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[5. 1.]
 [4. 9.]]
[[9. 1.]
 [5. 0.]]
[[5. 1.]
 [4. 9.]
 [9. 1.]
 [5. 0.]]
[[5. 1. 9. 1.]
 [4. 9. 5. 0.]]
