In [2]:
import numpy as np

In [ ]:
#创建3行2列二维数组。
a = np.array([[1,2],[3,4],[5,6]])

a = np.zeros(6)#创建长度为6的，元素都是0一维数组
a = np.zeros((2,3))#创建3行2列，元素都是0的二维数组
a = np.ones((2,3))#创建3行2列，元素都是1的二维数组
a = np.empty((2,3)) #创建3行2列,未初始化的二维数组

a = np.arange(6)#创建长度为6的，元素都是0一维数组array([0, 1, 2, 3, 4, 5])
a = np.arange(1,7,1)#结果与np.arange(6)一样。第一，二个参数意思是数值从1〜6,不包括7.第三个参数表步长为1.

a = np.linspace(0,10,7) # 生成首位是0，末位是10，含7个数的等差数列
a = np.logspace(0,4,5)#用于生成首位是10**0，末位是10**4，含5个数的等比数列。

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[10,20],[30,40],[50,60]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]
[[ 1  2 10 20]
 [ 3  4 30 40]
 [ 5  6 50 60]]


In [5]:
# 不同维数的数组直接相加显然是不允许的。但是可以用一个n行列向量和一个m列行向量构造出一个n×m矩阵
a = np.array([[1],[2]])
b=([[10,20,30]])#生成一个list，注意，不是np.array。
print(a+b)
c = np.array([10,20,30])
print(a+c)

[[11 21 31]
 [12 22 32]]
[[11 21 31]
 [12 22 32]]


In [10]:
a = np.array([[1, 2],[3, 4],[5, 6]])
print(a[0])
print(a[0][1])
print(a[0,1])

b = np.arange(6)#array([0, 1, 2, 3, 4, 5])
print(b[1:3])#右边开区间array([1, 2])
print(b[:3])#左边默认为0,array([0, 1, 2])
print(b[3:])#右边默认为元素个数,array([3, 4, 5])
print(b[0:4:2])#下标递增2,array([0, 2])

[1 2]
2
2
[1 2]
[0 1 2]
[3 4 5]
[0 2]


In [13]:
'''np.where(condition, x, y)，第一个参数为一个布尔数组，
第二个参数和第三个参数可以是标量也可以是数组。
'''
cond = np.array([1,2,3,4])
a = np.where(cond>2,-2,2)# [ 2 2 -2 -2]
b1 = np.array([-1,-2,-3,-4])
b2 = np.array([1,2,3,4])
print(np.where(cond>2,b1,b2)) # 长度须匹配# [1,2,-3,-4]

[ 1  2 -3 -4]


In [14]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
a[0] = [11,22]#修改第一行数组[1,2]为[11,22]。
print(a)
a[0][0] = 111#修改第一个元素为111,修改后，第一个元素“1”改为“111”。
print(a)

a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[10,20],[30,40],[50,60]])
print(a+b) #加法必须在两个相同大小的数组键间运算。

[[1 2]
 [3 4]
 [5 6]]
[[11 22]
 [ 3  4]
 [ 5  6]]
[[111  22]
 [  3   4]
 [  5   6]]
[[11 22]
 [33 44]
 [55 66]]


In [16]:
a = np.array([[1,2],[3,4],[5,6]])
print(a*2)#相当于a中各个元素都乘以2.类似于广播。
print(a**2)
print(a>3)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[False False]
 [False  True]
 [ True  True]]


In [23]:
# 利用查找中的方法，比如a=a[0]，操作完居后，a的行数只剩一行了。
a = np.array([[1,2],[3,4],[5,6]])
print(a[0])

a = np.array([[1,2],[3,4],[5,6]])
print(np.delete(a,1,axis = 0))#删除a的第二行。
print(np.delete(a,(1,2),0))#删除a的第二，三行。
print(np.delete(a,1,axis = 1))#删除a的第二列。
print(a)

# 先分割，再按切片a=a[0]赋值。
a = np.array([[1,2],[3,4],[5,6]])
print(np.hsplit(a,2))#水平分割（搞不懂，明明是垂直分割嘛？）
print(np.split(a,2,axis = 1))#与np.hsplit(a,2)效果一样。

print(np.vsplit(a,3))
print(np.split(a,3,axis = 0))#与np.vsplit(a,3)效果一样。

[1 2]
[[1 2]
 [5 6]]
[[1 2]]
[[1]
 [3]
 [5]]
[[1 2]
 [3 4]
 [5 6]]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
