In [6]:
import numpy as np
import pandas as pd

from IPython import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [7]:
arr1 = np.random.randint(1,10,10)
arr2 = np.random.randint(1,10,10)
arr1
arr2
np.intersect1d(arr1, arr2)

array([9, 9, 5, 6, 8, 8, 8, 9, 1, 1])

array([4, 9, 9, 4, 2, 7, 9, 2, 9, 8])

array([8, 9])

In [8]:
np.setdiff1d(arr1,arr2)


array([1, 5, 6])

In [9]:
arr1.flags.writeable = False
arr1[0] = 0

ValueError: assignment destination is read-only

In [10]:
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]})
df
df.values

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int64)

In [11]:
arr1 = np.random.randint(1,10,10)
arr2 = np.random.randint(1,10,10)
np.mean(arr1)
np.median(arr1)
np.var(arr1)
np.std(arr1)
np.cov(arr1,arr2)
np.corrcoef(arr1,arr2)


6.0

6.0

2.8

1.6733200530681511

array([[3.11111111, 1.66666667],
       [1.66666667, 7.77777778]])

array([[1.        , 0.33881546],
       [0.33881546, 1.        ]])

In [13]:
arr = np.arange(10)
arr
slc = slice(2,8,2)
arr[slc]  # arr[2,8,2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 4, 6])

In [16]:
str1 = ['I love']
str2 = [' Python']
np.char.add(str1,str2)


array(['I love Python'], dtype='<U13')

In [ ]:
arr = np.random.uniform(0,10,10)
arr
np.ceil(arr)
np.floor(arr)

In [17]:
np.set_printoptions(suppress=True)

In [22]:
arr = np.random.randint(1,10,[3,3])
arr

array([[8, 5, 9],
       [5, 6, 8],
       [9, 8, 2]])

In [28]:
arr[:,::-1]
arr[::-1]

array([[9, 5, 8],
       [8, 6, 5],
       [2, 8, 9]])

array([[9, 8, 2],
       [5, 6, 8],
       [8, 5, 9]])

array([[9, 8, 2],
       [5, 6, 8],
       [8, 5, 9]])

In [31]:
a = 10
b = 3

In [32]:
np.mod(a, b)
a % b


1

1

In [35]:
arr = np.random.randint(1,20,10)
arr
arr[(arr>1)&(arr<7)&(arr%2==0)]

array([ 7,  6,  2,  3, 17,  3, 11,  2,  3,  6])

array([6, 2, 2, 6])

In [40]:
arr
np.piecewise(arr, [arr<3, arr>=7], [-1, 1])

np.piecewise(arr,[a<3,a>=3], [-1])

array([[2],
       [4],
       [3]])

array([[-1],
       [ 0],
       [ 0]])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2

In [38]:
arr = np.random.randint(1,10,[3,1])
arr
np.squeeze(arr)
arr1 = arr.T
arr1
np.squeeze(arr1)


array([[2],
       [4],
       [3]])

array([2, 4, 3])

array([[2, 4, 3]])

array([2, 4, 3])

In [39]:
A = np.array([[1, 2, 3], [2, -1, 1], [3, 0, -1]])
b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)
x




array([ 2., -1.,  3.])