In [1]:
from IPython import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
%matplotlib auto

import numpy as np
print(np.__version__)

Using matplotlib backend: Qt5Agg
1.20.2


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [5]:
list1 = [1,2,3,4,5,6,7,8,9]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr = np.full((2,2),fill_value=True)
arr.dtype

dtype('bool')

In [8]:
np.linspace(start=5,stop=50,num=20)

array([ 5.        ,  7.36842105,  9.73684211, 12.10526316, 14.47368421,
       16.84210526, 19.21052632, 21.57894737, 23.94736842, 26.31578947,
       28.68421053, 31.05263158, 33.42105263, 35.78947368, 38.15789474,
       40.52631579, 42.89473684, 45.26315789, 47.63157895, 50.        ])

In [9]:
arr = np.linspace(start=5,stop=50,num=20,dtype=int)
arr
arr.dtype

array([ 5,  7,  9, 12, 14, 16, 19, 21, 23, 26, 28, 31, 33, 35, 38, 40, 42,
       45, 47, 50])

dtype('int32')

In [10]:
np.random.randint(0,10,size=(3,3))

array([[0, 5, 1],
       [2, 4, 6],
       [5, 0, 7]])

In [11]:
np.random.randn(2,3)

array([[-0.30363954,  0.51219631,  0.86164593],
       [-0.12940461, -0.42990639, -0.86276921]])

In [12]:
arr = np.array(range(9))
arr
arr = arr.reshape(3,3)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [14]:
arr.dtype


dtype('int32')

In [15]:
arr.nbytes

arr.itemsize
arr.itemsize * arr.shape[0] * arr.shape[1]

36

4

36

In [16]:
arr = arr.astype(float)
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [17]:
arr[2,2]

8.0

In [18]:
arr[2,2] = arr[2,2] * 10
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7., 80.]])

In [19]:
arr[arr%2==0]

array([ 0.,  2.,  4.,  6., 80.])

In [20]:
arr[arr%2==1]=666
arr

array([[  0., 666.,   2.],
       [666.,   4., 666.],
       [  6., 666.,  80.]])

In [21]:
result = np.diag([5,5,5,5,5])
result
a = result[:, [1,0,2,3,4]]
a

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

array([[0, 5, 0, 0, 0],
       [5, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [22]:
((a==result).all())

False

In [23]:
np.argwhere(a!=result)

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]], dtype=int64)

In [24]:
np.linalg.det(result)

3124.999999999999

In [25]:
np.vstack((a,result))

array([[0, 5, 0, 0, 0],
       [5, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5],
       [5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [26]:
new = np.pad(result,pad_width=1,constant_values=1)
new

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 5, 0, 0, 0, 0, 1],
       [1, 0, 5, 0, 0, 0, 1],
       [1, 0, 0, 5, 0, 0, 1],
       [1, 0, 0, 0, 5, 0, 1],
       [1, 0, 0, 0, 0, 5, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [27]:
np.argwhere(new>1)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]], dtype=int64)

In [28]:
new[new>1] = 9
new

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 9, 0, 0, 0, 0, 1],
       [1, 0, 9, 0, 0, 0, 1],
       [1, 0, 0, 9, 0, 0, 1],
       [1, 0, 0, 0, 9, 0, 1],
       [1, 0, 0, 0, 0, 9, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [29]:
np.sum(new, axis=0)

array([ 7, 11, 11, 11, 11, 11,  7])

In [30]:
new[2,1] = 3
new
np.sum(new, axis=1)


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 9, 0, 0, 0, 0, 1],
       [1, 3, 9, 0, 0, 0, 1],
       [1, 0, 0, 9, 0, 0, 1],
       [1, 0, 0, 0, 9, 0, 1],
       [1, 0, 0, 0, 0, 9, 1],
       [1, 1, 1, 1, 1, 1, 1]])

array([ 7, 11, 14, 11, 11, 11,  7])

In [31]:
data = np.random.randint(1,100,[6,6])
data

array([[19, 41, 56, 78, 52, 68],
       [26, 58, 56, 79, 15, 49],
       [44, 86, 75, 82, 26, 38],
       [23, 74, 25, 62, 19, 12],
       [17, 60,  4, 54, 50, 33],
       [ 5, 36,  6, 39, 75, 84]])

In [32]:
np.max(data, axis=0)

array([44, 86, 75, 82, 75, 84])

In [33]:
np.unique(data, return_counts=True)

(array([ 4,  5,  6, 12, 15, 17, 19, 23, 25, 26, 33, 36, 38, 39, 41, 44, 49,
        50, 52, 54, 56, 58, 60, 62, 68, 74, 75, 78, 79, 82, 84, 86]),
 array([1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 2, 1, 1, 1, 1, 1], dtype=int64))

In [34]:
data.argsort()

array([[0, 1, 4, 2, 5, 3],
       [4, 0, 5, 2, 1, 3],
       [4, 5, 0, 2, 3, 1],
       [5, 4, 0, 2, 3, 1],
       [2, 0, 5, 4, 3, 1],
       [0, 2, 1, 3, 4, 5]], dtype=int64)

In [35]:
data1 = np.repeat(data,2,axis=0)
data1

array([[19, 41, 56, 78, 52, 68],
       [19, 41, 56, 78, 52, 68],
       [26, 58, 56, 79, 15, 49],
       [26, 58, 56, 79, 15, 49],
       [44, 86, 75, 82, 26, 38],
       [44, 86, 75, 82, 26, 38],
       [23, 74, 25, 62, 19, 12],
       [23, 74, 25, 62, 19, 12],
       [17, 60,  4, 54, 50, 33],
       [17, 60,  4, 54, 50, 33],
       [ 5, 36,  6, 39, 75, 84],
       [ 5, 36,  6, 39, 75, 84]])

In [36]:
np.unique(data1, axis=0)

array([[ 5, 36,  6, 39, 75, 84],
       [17, 60,  4, 54, 50, 33],
       [19, 41, 56, 78, 52, 68],
       [23, 74, 25, 62, 19, 12],
       [26, 58, 56, 79, 15, 49],
       [44, 86, 75, 82, 26, 38]])

In [37]:
np.random.choice(data[0], 3)

array([78, 56, 78])

In [38]:
idx = np.isin(data[2],data[3])
arr = data[2, ~idx]
arr


array([44, 86, 75, 82, 26, 38])

In [41]:
data.any(axis=1)
(~data.any(axis=1)).any()

array([ True,  True,  True,  True,  True,  True])

False

In [42]:
data.sort(axis=1)
data

array([[19, 41, 52, 56, 68, 78],
       [15, 26, 49, 56, 58, 79],
       [26, 38, 44, 75, 82, 86],
       [12, 19, 23, 25, 62, 74],
       [ 4, 17, 33, 50, 54, 60],
       [ 5,  6, 36, 39, 75, 84]])

In [44]:
data1 = data.astype(float)
data1

array([[19., 41., 52., 56., 68., 78.],
       [15., 26., 49., 56., 58., 79.],
       [26., 38., 44., 75., 82., 86.],
       [12., 19., 23., 25., 62., 74.],
       [ 4., 17., 33., 50., 54., 60.],
       [ 5.,  6., 36., 39., 75., 84.]])

In [48]:
np.isnan(data1).any()
data1 = data1[~np.isnan(data1).any(axis=1)]
data1

False

array([[19., 41., 52., 56., 68., 78.],
       [15., 26., 49., 56., 58., 79.],
       [26., 38., 44., 75., 82., 86.],
       [12., 19., 23., 25., 62., 74.],
       [ 4., 17., 33., 50., 54., 60.],
       [ 5.,  6., 36., 39., 75., 84.]])

In [52]:
data1[0,2] = 19
vals, counts = np.unique(data1[0], return_counts=True)
counts[counts>1]
vals[np.argmax(counts)]

array([2], dtype=int64)

19.0

In [55]:
a = 100
np.abs(data1 - a).argmin()
data1.flat[np.abs(data1 - a).argmin()]

17

86.0

In [57]:
data1.mean(axis=1)
data1.mean(axis=1, keepdims=True)

array([46.83333333, 47.16666667, 58.5       , 35.83333333, 36.33333333,
       40.83333333])

array([[46.83333333],
       [47.16666667],
       [58.5       ],
       [35.83333333],
       [36.33333333],
       [40.83333333]])

In [58]:
a = np.max(data1) - np.min(data1)
(data1 - np.min(data1)) / a

array([[0.18292683, 0.45121951, 0.18292683, 0.63414634, 0.7804878 ,
        0.90243902],
       [0.13414634, 0.26829268, 0.54878049, 0.63414634, 0.65853659,
        0.91463415],
       [0.26829268, 0.41463415, 0.48780488, 0.86585366, 0.95121951,
        1.        ],
       [0.09756098, 0.18292683, 0.23170732, 0.25609756, 0.70731707,
        0.85365854],
       [0.        , 0.15853659, 0.35365854, 0.56097561, 0.6097561 ,
        0.68292683],
       [0.01219512, 0.02439024, 0.3902439 , 0.42682927, 0.86585366,
        0.97560976]])

In [59]:
mu = np.mean(data1, axis=0)
sigma = np.std(data1, axis=0)
(data1 - mu) / sigma






array([[ 0.71654522,  1.35820488, -1.41316716,  0.37617015,  0.15478181,
         0.13736056],
       [ 0.19542142,  0.12347317,  1.41316716,  0.37617015, -0.87709693,
         0.25509819],
       [ 1.62851187,  1.11125854,  0.94211144,  1.60141009,  1.59941205,
         1.07926157],
       [-0.19542142, -0.45273496, -1.03632258, -1.62290552, -0.46434543,
        -0.33358994],
       [-1.23766902, -0.61736585, -0.09421114, -0.01074772, -1.28984843,
        -1.98191671],
       [-1.10738807, -1.52283577,  0.18842229, -0.72009715,  0.87709693,
         0.84378632]])