In [16]:
import numpy as np
import pandas as pd

from IPython import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [12]:

def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

data = np.array([10,5,8,9,15,22,6,1,15,7])
ma = moving_average(data,4)

print(ma)

np.convolve(data, np.ones(4), 'valid') / 4
np.convolve(data, np.ones(4), 'same') / 4
np.convolve(data, np.ones(4), 'full') / 4

[ 8.    9.25 13.5  13.   11.   11.    7.25]


array([ 8.  ,  9.25, 13.5 , 13.  , 11.  , 11.  ,  7.25])

array([ 3.75,  5.75,  8.  ,  9.25, 13.5 , 13.  , 11.  , 11.  ,  7.25,
        5.75])

array([ 2.5 ,  3.75,  5.75,  8.  ,  9.25, 13.5 , 13.  , 11.  , 11.  ,
        7.25,  5.75,  5.5 ,  1.75])

In [13]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

moving_average(data,4)


array([ 8.  ,  9.25, 13.5 , 13.  , 11.  , 11.  ,  7.25])

In [14]:
import bottleneck as bn
import numpy as np
def rollavg_bottlneck(a,n):
    return bn.move_mean(a, window=n,min_count = None)

rollavg_bottlneck(data, 4)

array([  nan,   nan,   nan,  8.  ,  9.25, 13.5 , 13.  , 11.  , 11.  ,
        7.25])

In [17]:
df = pd.Series(data)

df.rolling(4).mean()


0      NaN
1      NaN
2      NaN
3     8.00
4     9.25
5    13.50
6    13.00
7    11.00
8    11.00
9     7.25
dtype: float64