In [1]:
import os

import pandas as pd
import numpy as np

from IPython import InteractiveShell

from util.ConstUtil import DATA_PATH

InteractiveShell.ast_node_interactivity = "all"

In [2]:
data_path = os.path.join(DATA_PATH, 'pandas_rs')
fpath = os.path.join(data_path, '数据1.csv')
df = pd.read_csv(fpath, encoding='gbk', usecols=['positionName', 'salary'], nrows=10)
df

positionName  salary
0         数据分析   37500
1         数据建模   15000
2         数据分析    3500
3         数据分析   45000
4         数据分析   30000
5         数据分析   50000
6         数据分析   30000
7      数据建模工程师   35000
8       数据分析专家   60000
9        数据分析师   40000

In [3]:
fpath = os.path.join(data_path, '数据2.csv')
df = pd.read_csv(fpath, converters={'薪资水平':lambda x: '高' if float(x)>10000 else '低'})
df
df.columns

学历要求 薪资水平
0      本科    高
1      硕士    高
2      本科    低
3      本科    高
4      不限    高
...   ...  ...
1149   硕士    高
1150   本科    高
1151   本科    高
1152   本科    高
1153   本科    高

[1154 rows x 2 columns]

Index(['学历要求', '薪资水平'], dtype='object')

In [4]:
df.loc[::20,'薪资水平']
df.iloc[::20][['薪资水平']]

0       高
20      高
40      高
60      高
80      高
100     高
120     高
140     高
160     高
180     高
200     高
220     高
240     高
260     高
280     低
300     高
320     高
340     低
360     高
380     高
400     高
420     高
440     高
460     低
480     高
500     高
520     高
540     高
560     高
580     高
600     高
620     高
640     高
660     低
680     低
700     高
720     高
740     高
760     高
780     高
800     高
820     高
840     高
860     低
880     高
900     高
920     高
940     高
960     高
980     高
1000    高
1020    高
1040    高
1060    高
1080    高
1100    高
1120    高
1140    高
Name: 薪资水平, dtype: object

薪资水平
0       高
20      高
40      高
60      高
80      高
100     高
120     高
140     高
160     高
180     高
200     高
220     高
240     高
260     高
280     低
300     高
320     高
340     低
360     高
380     高
400     高
420     高
440     高
460     低
480     高
500     高
520     高
540     高
560     高
580     高
600     高
620     高
640     高
660     低
680     低
700     高
720     高
740     高
760     高
780     高
800     高
820     高
840     高
860     低
880     高
900     高
920     高
940     高
960     高
980     高
1000    高
1020    高
1040    高
1060    高
1080    高
1100    高
1120    高
1140    高

In [5]:
df = pd.DataFrame(np.random.random(10)**10,columns=['data'])
df = df.round(3)
df

data
0  0.001
1  0.000
2  0.019
3  0.000
4  0.000
5  0.341
6  0.000
7  0.000
8  0.001
9  0.021

In [6]:
df.style.format({'data': '{0:.2%}'})


In [7]:
df['data'].argsort()
df['data'].argsort()[7]

df['data1'] = df['data'] * -1
df['data1'].argsort()[2]


0    1
1    3
2    4
3    6
4    7
5    0
6    8
7    2
8    9
9    5
Name: data, dtype: int64

2

2

In [8]:
df1 = df.iloc[::-1].reset_index()
df1

index   data  data1
0      9  0.021 -0.021
1      8  0.001 -0.001
2      7  0.000 -0.000
3      6  0.000 -0.000
4      5  0.341 -0.341
5      4  0.000 -0.000
6      3  0.000 -0.000
7      2  0.019 -0.019
8      1  0.000 -0.000
9      0  0.001 -0.001

In [9]:
df1= pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
'key2': ['K0', 'K1', 'K0', 'K1'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})

df2= pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
'key2': ['K0', 'K0', 'K0', 'K0'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(df1, df2, on=['key1', 'key2'])


key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [10]:
pd.merge(df1, df2, on=['key1', 'key2'], how='left')


key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [19]:
fpath = os.path.join(data_path, '数据1.csv')
df:pd.DataFrame = pd.read_csv(fpath, encoding='gbk')

In [20]:
np.where(df.secondType == df.thirdType)

(array([  0,   2,   4,   5,   6,  10,  14,  23,  25,  27,  28,  29,  30,
         33,  37,  38,  39,  40,  41,  48,  49,  52,  53,  55,  57,  61,
         65,  66,  67,  71,  73,  74,  75,  79,  80,  82,  85,  88,  89,
         91,  96, 100], dtype=int64),)

In [21]:
df['salary'].values > df['salary'].mean()
np.argwhere(df['salary'].values>df['salary'].mean())

array([ True, False, False,  True, False,  True, False,  True,  True,
        True, False, False, False, False,  True, False,  True,  True,
       False,  True, False, False, False, False, False,  True,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
        True, False,  True,  True, False,  True, False,  True,  True,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False,  True, False, False,  True, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True, False, False, False, False,  True, False, False,
        True,  True, False, False, False,  True, False, False, False,
        True, False,  True, False, False, False])

array([[  0],
       [  3],
       [  5],
       [  7],
       [  8],
       [  9],
       [ 14],
       [ 16],
       [ 17],
       [ 19],
       [ 25],
       [ 26],
       [ 28],
       [ 29],
       [ 30],
       [ 32],
       [ 35],
       [ 36],
       [ 38],
       [ 39],
       [ 41],
       [ 43],
       [ 44],
       [ 46],
       [ 47],
       [ 57],
       [ 60],
       [ 64],
       [ 66],
       [ 69],
       [ 77],
       [ 79],
       [ 82],
       [ 87],
       [ 90],
       [ 91],
       [ 95],
       [ 99],
       [101]], dtype=int64)

In [22]:
df['salary'].apply(np.sqrt)

0      193.649167
1      122.474487
2       59.160798
3      212.132034
4      173.205081
          ...    
100    158.113883
101    187.082869
102    173.205081
103    141.421356
104    146.628783
Name: salary, Length: 105, dtype: float64

In [25]:
df['split'] = df['linestaion'].str.split('_')
df.head()


positionId positionName  companyId  \
0     6802721         数据分析     475770   
1     5204912         数据建模      50735   
2     6877668         数据分析     100125   
3     6496141         数据分析      26564   
4     6467417         数据分析      29211   

                                         companyLogo companySize  \
0  i/image2/M01/B7/3E/CgoB5lwPfEaAdn8WAABWQ0Jgl5s...     50-150人   
1  image1/M00/00/85/CgYXBlTUXeeAR0IjAABbroUk-dw97...    150-500人   
2  image2/M00/0C/57/CgqLKVYcOA2ADcFuAAAE8MukIKA74...     2000人以上   
3  i/image2/M01/F7/3F/CgoB5lyGAQGAZeI-AAAdOqXecnw...   500-2000人   
4  i/image2/M01/77/B8/CgoB5l1WDyGATNP5AAAlY3h88SY...     2000人以上   

  industryField financeStage                   companyLabelList  firstType  \
0      移动互联网,电商           A轮   ['绩效奖金', '带薪年假', '定期体检', '弹性工作']  产品|需求|项目类   
1            电商           B轮   ['年终奖金', '做五休二', '六险一金', '子女福利']  开发|测试|运维类   
2    移动互联网,企业服务         上市公司   ['节日礼物', '年底双薪', '股票期权', '带薪年假']  产品|需求|项目类   
3            电商        D轮及以上  ['生日趴', '每月腐败基金', '每月补贴', '年度旅游']  开发|测试|运维类   
4         物流丨运输         上市公司   ['技能培训', '免费班车', '专项奖金', '岗位晋升']  产品|需求|项目类   

  secondType  ... pcShow appShow deliver gradeDescription  \
0       数据分析  ...      0       0       0              NaN   
1       数据开发  ...      0       0       0              NaN   
2       数据分析  ...      0       0       0              NaN   
3       数据开发  ...      0       0       0              NaN   
4       数据分析  ...      0       0       0              NaN   

  promotionScoreExplain isHotHire count aggregatePositionIds  famousCompany  \
0                   NaN         0     0                   []          False   
1                   NaN         0     0                   []          False   
2                   NaN         0     0                   []          False   
3                   NaN         0     0                   []           True   
4                   NaN         0     0                   []           True   

                           split  
0                            NaN  
1                            NaN  
2  [4号线, 城星路;4号线, 市民中心;4号线, 江锦路]  
3                     [1号线, 文泽路]  
4                            NaN  

[5 rows x 54 columns]

In [28]:
df.shape[1]


54

In [31]:
df[df['industryField'].str.startswith('数据')]

positionId        positionName  companyId  \
8      6458372              数据分析专家      34132   
10     6804629               数据分析师      34132   
13     6804489             资深数据分析师      34132   
21     6267370              数据分析专家      31544   
32     6804489             资深数据分析师      34132   
37     6242470               数据分析师      31544   
50     6680900    数据分析师 (MJ000250)     114335   
63     6680900    数据分析师 (MJ000250)     114335   
78     5683671  数据分析实习生 (MJ000087)     114335   
79     6046866               数据分析师     543802   
92     6813626            资深数据分析专员     165939   
94     6818950             资深数据分析师     165939   
97     6718750        旅游大数据分析师（杭州）     122019   
98     6655562           数据分析建模工程师  117422215   
99     6677939       数据分析建模工程师（校招）  117422215   

                                          companyLogo companySize  \
8   i/image2/M01/F8/DE/CgoB5lyHTJeAP7v9AAFXUt4zJo4...    150-500人   
10  i/image2/M01/F8/DE/CgoB5lyHTJeAP7v9AAFXUt4zJo4...    150-500人   
13  i/image2/M01/F8/DE/CgoB5lyHTJeAP7v9AAFXUt4zJo4...    150-500人   
21  image1/M00/00/48/CgYXBlTUXOaADKooAABjQoD_n1w50...    150-500人   
32  i/image2/M01/F8/DE/CgoB5lyHTJeAP7v9AAFXUt4zJo4...    150-500人   
37  image1/M00/00/48/CgYXBlTUXOaADKooAABjQoD_n1w50...    150-500人   
50  i/image2/M00/17/C2/CgoB5ln5lUuAM8oSAADO2Rz54hQ...    150-500人   
63  i/image2/M00/17/C2/CgoB5ln5lUuAM8oSAADO2Rz54hQ...    150-500人   
78  i/image2/M00/17/C2/CgoB5ln5lUuAM8oSAADO2Rz54hQ...    150-500人   
79  i/image2/M01/63/3C/CgotOV0ulwOAU8KWAAAsMECc53M...      15-50人   
92  i/image3/M01/65/71/CgpOIF5CFp2ACoo9AAD3IkKwlv8...    150-500人   
94  i/image3/M01/65/71/CgpOIF5CFp2ACoo9AAD3IkKwlv8...    150-500人   
97  i/image/M00/1A/4A/CgqKkVb583WABT4BAABM5RuPCmk9...     50-150人   
98  i/image2/M01/AF/6D/CgotOV3ki4iAOuo3AABbilI8DfA...     50-150人   
99  i/image2/M01/AF/6D/CgotOV3ki4iAOuo3AABbilI8DfA...     50-150人   

   industryField financeStage                     companyLabelList  firstType  \
8      数据服务,广告营销           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  产品|需求|项目类   
10     数据服务,广告营销           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  产品|需求|项目类   
13     数据服务,广告营销           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  开发|测试|运维类   
21          数据服务        不需要融资   ['专业红娘牵线', '节日礼物', '技能培训', '岗位晋升']  开发|测试|运维类   
32     数据服务,广告营销           A轮  ['开放式办公', '扁平管理', '带薪假期', '弹性工作时间']  开发|测试|运维类   
37          数据服务        不需要融资   ['专业红娘牵线', '节日礼物', '技能培训', '岗位晋升']  产品|需求|项目类   
50          数据服务           B轮      ['股票期权', '弹性工作', '领导好', '五险一金']  产品|需求|项目类   
63          数据服务           B轮      ['股票期权', '弹性工作', '领导好', '五险一金']  产品|需求|项目类   
78          数据服务           B轮      ['股票期权', '弹性工作', '领导好', '五险一金']  开发|测试|运维类   
79          数据服务        不需要融资                                   []  产品|需求|项目类   
92          数据服务        不需要融资     ['年底双薪', '带薪年假', '午餐补助', '定期体检']  开发|测试|运维类   
94          数据服务        不需要融资     ['年底双薪', '带薪年假', '午餐补助', '定期体检']  开发|测试|运维类   
97     数据服务,企业服务           A轮     ['年底双薪', '股票期权', '午餐补助', '定期体检']  开发|测试|运维类   
98     数据服务,信息安全           A轮  ['午餐补助', '带薪年假', '16到18薪', '法定节假日']  开发|测试|运维类   
99     数据服务,信息安全           A轮  ['午餐补助', '带薪年假', '16到18薪', '法定节假日']  开发|测试|运维类   

   secondType  ... pcShow appShow deliver gradeDescription  \
8        数据分析  ...      0       0       0              NaN   
10       数据分析  ...      0       0       0              NaN   
13       数据开发  ...      0       0       0              NaN   
21       数据开发  ...      0       0       0              NaN   
32       数据开发  ...      0       0       0              NaN   
37       数据分析  ...      0       0       0              NaN   
50       产品经理  ...      0       0       0              NaN   
63       产品经理  ...      0       0       0              NaN   
78       后端开发  ...      0       0       0              NaN   
79       数据分析  ...      0       0       0              NaN   
92       数据开发  ...      0       0       0              NaN   
94       数据开发  ...      0       0       0              NaN   
97       数据

In [33]:
pd.pivot_table(df,values=['salary','score'],index='positionId')

salary  score
positionId               
5203054      30000    4.0
5204912      15000  176.0
5269002      37500    1.0
5453691      30000    4.0
5519962      37500   14.0
...            ...    ...
6882983      27500   15.0
6884346      25000    0.0
6886661      37500    5.0
6888169      42500    1.0
6896403      30000    3.0

[95 rows x 2 columns]

In [35]:
df[['salary','score']].agg([np.sum,np.mean,np.min])

salary        score
sum   3.331000e+06  1335.000000
mean  3.172381e+04    12.714286
amin  3.500000e+03     0.000000

In [37]:
df[['district','salary']].groupby(by='district').mean().sort_values('salary',ascending=False).head(5)


salary
district              
萧山区       36250.000000
余杭区       33583.333333
滨江区       31428.571429
西湖区       30893.939394
下沙        30000.000000