In [1]:
import os
import pandas as pd
import numpy as np
from IPython import InteractiveShell
import matplotlib.pyplot as plt

from util.ConstUtil import DATA_PATH

InteractiveShell.ast_node_interactivity = "all"
%matplotlib auto


plt.rcParams['font.sans-serif'] = ['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False #用来正常显示负号
# plt.style.use('seaborn-darkgrid') # 设置画图的风格，不支持中文
# plt.rc('font',  size=6) #设置图中字体和大小


Using matplotlib backend: Qt5Agg


In [2]:
data_path = os.path.join(DATA_PATH, 'pandas_rs')
fpath = os.path.join(data_path, '600000.SH.xls')
data:pd.DataFrame = pd.read_excel(fpath)
data.head(10)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero


代码    简称         日期  前收盘价(元)   开盘价(元)   最高价(元)   最低价(元)   收盘价(元)  \
0  600000.SH  浦发银行 2016-01-04  16.1356  16.1444  16.1444  15.4997  15.7205   
1  600000.SH  浦发银行 2016-01-05  15.7205  15.4644  15.9501  15.3672  15.8618   
2  600000.SH  浦发银行 2016-01-06  15.8618  15.8088  16.0208  15.6234  15.9855   
3  600000.SH  浦发银行 2016-01-07  15.9855  15.7205  15.8088  15.3672  15.4644   
4  600000.SH  浦发银行 2016-01-08  15.4644  15.6675  15.7912  14.9345  15.4467   
5  600000.SH  浦发银行 2016-01-11  15.4467  15.1994  15.4114  14.9786  15.0581   
6  600000.SH  浦发银行 2016-01-12  15.0581  15.1641  15.4732  15.0846  15.4114   
7  600000.SH  浦发银行 2016-01-13  15.4114  15.5174  15.8088  15.3231  15.3584   
8  600000.SH  浦发银行 2016-01-14  15.3584  15.0140  15.8883  14.9168  15.8265   
9  600000.SH  浦发银行 2016-01-15  15.8265  15.7205  16.0296  15.4732  15.5262   

     成交量(股)     成交金额(元)   涨跌(元)  涨跌幅(%)    均价(元)  换手率(%)     A股流通市值(元)  \
0  42240610   754425783 -0.4151 -2.5725  17.8602  0.2264  3.320318e+11   
1  58054793  1034181474  0.1413  0.8989  17.8139  0.3112  3.350163e+11   
2  46772653   838667398  0.1236  0.7795  17.9307  0.2507  3.376278e+11   
3  11350479   199502702 -0.5211 -3.2597  17.5766  0.0608  3.266223e+11   
4  71918296  1262105060 -0.0177 -0.1142  17.5492  0.3855  3.262492e+11   
5  90177135  1550155933 -0.3886 -2.5157  17.1901  0.4834  3.180417e+11   
6  55374454   964061502  0.3533  2.3460  17.4099  0.2969  3.255031e+11   
7  47869312   843717365 -0.0530 -0.3438  17.6254  0.2566  3.243839e+11   
8  54838833   966117848  0.4681  3.0477  17.6174   0.294  3.342702e+11   
9  46723139   836146426 -0.3003 -1.8973  17.8958  0.2505  3.279280e+11   

         总市值(元)     A股流通股本(股)     市盈率  
0  3.320318e+11  1.865347e+10  6.5614  
1  3.350163e+11  1.865347e+10  6.6204  
2  3.376278e+11  1.865347e+10  6.6720  
3  3.266223e+11  1.865347e+10  6.4545  
4  3.262492e+11  1.865347e+10  6.4471  
5  3.180417e+11  1.865347e+10  6.2849  
6  3.255031e+11  1.865347e+10  6.4324  
7  3.243839e+11  1.865347e+10  6.4102  
8  3.342702e+11  1.865347e+10  6.6056  
9  3.279280e+11  1.865347e+10  6.4803

In [3]:
data.isnull().sum()

代码           1
简称           2
日期           2
前收盘价(元)      2
开盘价(元)       2
最高价(元)       2
最低价(元)       2
收盘价(元)       2
成交量(股)       2
成交金额(元)      2
涨跌(元)        2
涨跌幅(%)       2
均价(元)        2
换手率(%)       2
A股流通市值(元)    2
总市值(元)       2
A股流通股本(股)    2
市盈率          2
dtype: int64

In [4]:
for colname in data.columns:
	if data[colname].count() != len(data[colname]):
		loc = data[colname][data[colname].isnull()].index.tolist()
		print(f'列名：{colname}，第{loc}行位置有缺失值')

列名：代码，第[327]行位置有缺失值
列名：简称，第[327, 328]行位置有缺失值
列名：日期，第[327, 328]行位置有缺失值
列名：前收盘价(元)，第[327, 328]行位置有缺失值
列名：开盘价(元)，第[327, 328]行位置有缺失值
列名：最高价(元)，第[327, 328]行位置有缺失值
列名：最低价(元)，第[327, 328]行位置有缺失值
列名：收盘价(元)，第[327, 328]行位置有缺失值
列名：成交量(股)，第[327, 328]行位置有缺失值
列名：成交金额(元)，第[327, 328]行位置有缺失值
列名：涨跌(元)，第[327, 328]行位置有缺失值
列名：涨跌幅(%)，第[327, 328]行位置有缺失值
列名：均价(元)，第[327, 328]行位置有缺失值
列名：换手率(%)，第[327, 328]行位置有缺失值
列名：A股流通市值(元)，第[327, 328]行位置有缺失值
列名：总市值(元)，第[327, 328]行位置有缺失值
列名：A股流通股本(股)，第[327, 328]行位置有缺失值
列名：市盈率，第[327, 328]行位置有缺失值


In [5]:
data.dropna(axis=0, how='any', inplace=True)
data.isnull().sum(axis=0)

代码           0
简称           0
日期           0
前收盘价(元)      0
开盘价(元)       0
最高价(元)       0
最低价(元)       0
收盘价(元)       0
成交量(股)       0
成交金额(元)      0
涨跌(元)        0
涨跌幅(%)       0
均价(元)        0
换手率(%)       0
A股流通市值(元)    0
总市值(元)       0
A股流通股本(股)    0
市盈率          0
dtype: int64

In [6]:
# data['收盘价(元)'].plot()
data[['开盘价(元)','收盘价(元)']].plot()

<AxesSubplot:>

In [7]:
# data['涨跌幅(%)'].hist()
plt.hist(data['涨跌幅(%)'])

(array([  1.,   0.,   1.,   7.,  32., 224.,  53.,   5.,   2.,   2.]),
 array([-8.0217 , -6.59525, -5.1688 , -3.74235, -2.3159 , -0.88945,
         0.537  ,  1.96345,  3.3899 ,  4.81635,  6.2428 ]),
 <BarContainer object of 10 artists>)

In [8]:
data['涨跌幅(%)'].hist(bins=30)


<AxesSubplot:>

In [9]:
temp = pd.DataFrame(columns=data.columns.tolist())
temp


Empty DataFrame
Columns: [代码, 简称, 日期, 前收盘价(元), 开盘价(元), 最高价(元), 最低价(元), 收盘价(元), 成交量(股), 成交金额(元), 涨跌(元), 涨跌幅(%), 均价(元), 换手率(%), A股流通市值(元), 总市值(元), A股流通股本(股), 市盈率]
Index: []

In [10]:
temp = pd.to_numeric(data['换手率(%)'], errors='coerce')
np.where(temp.isnull())

(array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43], dtype=int64),)

In [11]:
data[data['换手率(%)'].isin(['--'])].head()

data[data['换手率(%)']=='--'].head()

代码    简称         日期  前收盘价(元)   开盘价(元)   最高价(元)   最低价(元)   收盘价(元)  \
26  600000.SH  浦发银行 2016-02-16  16.2946  16.2946  16.2946  16.2946  16.2946   
27  600000.SH  浦发银行 2016-02-17  16.2946  16.2946  16.2946  16.2946  16.2946   
28  600000.SH  浦发银行 2016-02-18  16.2946  16.2946  16.2946  16.2946  16.2946   
29  600000.SH  浦发银行 2016-02-19  16.2946  16.2946  16.2946  16.2946  16.2946   
30  600000.SH  浦发银行 2016-02-22  16.2946  16.2946  16.2946  16.2946  16.2946   

   成交量(股) 成交金额(元)  涨跌(元)  涨跌幅(%) 均价(元) 换手率(%)     A股流通市值(元)        总市值(元)  \
26     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
27     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
28     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
29     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
30     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   

       A股流通股本(股)    市盈率  
26  1.865347e+10  6.801  
27  1.865347e+10  6.801  
28  1.865347e+10  6.801  
29  1.865347e+10  6.801  
30  1.865347e+10  6.801

代码    简称         日期  前收盘价(元)   开盘价(元)   最高价(元)   最低价(元)   收盘价(元)  \
26  600000.SH  浦发银行 2016-02-16  16.2946  16.2946  16.2946  16.2946  16.2946   
27  600000.SH  浦发银行 2016-02-17  16.2946  16.2946  16.2946  16.2946  16.2946   
28  600000.SH  浦发银行 2016-02-18  16.2946  16.2946  16.2946  16.2946  16.2946   
29  600000.SH  浦发银行 2016-02-19  16.2946  16.2946  16.2946  16.2946  16.2946   
30  600000.SH  浦发银行 2016-02-22  16.2946  16.2946  16.2946  16.2946  16.2946   

   成交量(股) 成交金额(元)  涨跌(元)  涨跌幅(%) 均价(元) 换手率(%)     A股流通市值(元)        总市值(元)  \
26     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
27     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
28     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
29     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   
30     --      --    0.0     0.0    --     --  3.441565e+11  3.441565e+11   

       A股流通股本(股)    市盈率  
26  1.865347e+10  6.801  
27  1.865347e+10  6.801  
28  1.865347e+10  6.801  
29  1.865347e+10  6.801  
30  1.865347e+10  6.801

In [12]:
temp = pd.to_numeric(data['换手率(%)'], errors='coerce')
idx = np.where(temp.isnull())[0]

len(data)
data.drop(labels=idx, inplace=True)
len(data)

327

309

In [24]:
data['换手率(%)'].plot(kind='kde')
data['换手率(%)'].hist()

<AxesSubplot:ylabel='Density'>

<AxesSubplot:ylabel='Density'>

In [14]:
data['收盘价(元)'].pct_change()

0           NaN
1      0.008988
2      0.007799
3     -0.032598
4     -0.001145
         ...   
322   -0.005277
323   -0.006631
324   -0.004005
325   -0.004021
326   -0.006729
Name: 收盘价(元), Length: 309, dtype: float64

In [15]:
data.set_index('日期', inplace=True)

In [16]:
data['收盘价(元)'].rolling(5).mean()

日期
2016-01-04         NaN
2016-01-05         NaN
2016-01-06         NaN
2016-01-07         NaN
2016-01-08    15.69578
                ...   
2017-05-03    15.14200
2017-05-04    15.12800
2017-05-05    15.07000
2017-05-08    15.00000
2017-05-09    14.92000
Name: 收盘价(元), Length: 309, dtype: float64

In [17]:
data['收盘价(元)'].rolling(5).sum()

日期
2016-01-04        NaN
2016-01-05        NaN
2016-01-06        NaN
2016-01-07        NaN
2016-01-08    78.4789
               ...   
2017-05-03    75.7100
2017-05-04    75.6400
2017-05-05    75.3500
2017-05-08    75.0000
2017-05-09    74.6000
Name: 收盘价(元), Length: 309, dtype: float64

In [18]:
data['收盘价(元)'].plot()
data['收盘价(元)'].rolling(5).mean().plot()
data['收盘价(元)'].rolling(20).mean().plot()

<AxesSubplot:xlabel='日期', ylabel='Density'>

<AxesSubplot:xlabel='日期', ylabel='Density'>

<AxesSubplot:xlabel='日期', ylabel='Density'>

In [19]:
temp = pd.DataFrame()
temp['close'] = data['收盘价(元)']
temp['ma5'] = data['收盘价(元)'].rolling(5).mean()
temp['ma20'] = data['收盘价(元)'].rolling(20).mean()
temp.plot()

<AxesSubplot:xlabel='日期'>

In [20]:
data['收盘价(元)'].resample('W').max()

日期
2016-01-10    15.9855
2016-01-17    15.8265
2016-01-24    15.6940
2016-01-31    15.0405
2016-02-07    16.2328
               ...   
2017-04-16    15.9700
2017-04-23    15.5600
2017-04-30    15.2100
2017-05-07    15.1600
2017-05-14    14.8600
Freq: W-SUN, Name: 收盘价(元), Length: 71, dtype: float64

In [21]:
# temp = pd.DataFrame(data['收盘价(元)'])
# temp['weekly'] = data['收盘价(元)'].resample('7D').max()
# temp.plot()
data['收盘价(元)'].plot()
data['收盘价(元)'].resample('7D').max().plot()

<AxesSubplot:xlabel='日期'>

<AxesSubplot:xlabel='日期'>

In [22]:
data.shift(3)

代码    简称  前收盘价(元)   开盘价(元)   最高价(元)   最低价(元)   收盘价(元)  \
日期                                                                         
2016-01-04        NaN   NaN      NaN      NaN      NaN      NaN      NaN   
2016-01-05        NaN   NaN      NaN      NaN      NaN      NaN      NaN   
2016-01-06        NaN   NaN      NaN      NaN      NaN      NaN      NaN   
2016-01-07  600000.SH  浦发银行  16.1356  16.1444  16.1444  15.4997  15.7205   
2016-01-08  600000.SH  浦发银行  15.7205  15.4644  15.9501  15.3672  15.8618   
...               ...   ...      ...      ...      ...      ...      ...   
2017-05-03  600000.SH  浦发银行  15.0500  15.0500  15.2500  15.0300  15.2100   
2017-05-04  600000.SH  浦发银行  15.2100  15.1500  15.2200  15.0800  15.2100   
2017-05-05  600000.SH  浦发银行  15.2100  15.2100  15.2200  15.1300  15.1600   
2017-05-08  600000.SH  浦发银行  15.1600  15.1600  15.1600  15.0500  15.0800   
2017-05-09  600000.SH  浦发银行  15.0800  15.0700  15.0700  14.9000  14.9800   

              成交量(股)     成交金额(元)   涨跌(元)  涨跌幅(%)    均价(元)  换手率(%)  \
日期                                                                  
2016-01-04       NaN         NaN     NaN     NaN      NaN     NaN   
2016-01-05       NaN         NaN     NaN     NaN      NaN     NaN   
2016-01-06       NaN         NaN     NaN     NaN      NaN     NaN   
2016-01-07  42240610   754425783 -0.4151 -2.5725  17.8602  0.2264   
2016-01-08  58054793  1034181474  0.1413  0.8989  17.8139  0.3112   
...              ...         ...     ...     ...      ...     ...   
2017-05-03  22887645   345791526  0.1600  1.0631  15.1082  0.1059   
2017-05-04  15718509   238419161  0.0000  0.0000  15.1681  0.0727   
2017-05-05  12607509   191225527 -0.0500 -0.3287  15.1676  0.0583   
2017-05-08  14247943   215130847 -0.0800 -0.5277  15.0991  0.0659   
2017-05-09  19477788   291839737 -0.1000 -0.6631  14.9832  0.0901   

               A股流通市值(元)        总市值(元)     A股流通股本(股)     市盈率  
日期                                                            
2016-01-04           NaN           NaN           NaN     NaN  
2016-01-05           NaN           NaN           NaN     NaN  
2016-01-06           NaN           NaN           NaN     NaN  
2016-01-07  3.320318e+11  3.320318e+11  1.865347e+10  6.5614  
2016-01-08  3.350163e+11  3.350163e+11  1.865347e+10  6.6204  
...                  ...           ...           ...     ...  
2017-05-03  3.288140e+11  3.288140e+11  2.161828e+10  6.1925  
2017-05-04  3.288140e+11  3.288140e+11  2.161828e+10  6.1925  
2017-05-05  3.277331e+11  3.277331e+11  2.161828e+10  6.1721  
2017-05-08  3.260037e+11  3.260037e+11  2.161828e+10  6.1395  
2017-05-09  3.238418e+11  3.238418e+11  2.161828e+10  6.0988  

[309 rows x 17 columns]

In [23]:
data.shift(-3).tail()

代码    简称  前收盘价(元)  开盘价(元)  最高价(元)  最低价(元)  收盘价(元)  \
日期                                                                     
2017-05-03  600000.SH  浦发银行    14.92   14.78   14.90   14.51   14.86   
2017-05-04  600000.SH  浦发银行    14.86   14.69   14.84   14.66   14.76   
2017-05-05        NaN   NaN      NaN     NaN     NaN     NaN     NaN   
2017-05-08        NaN   NaN      NaN     NaN     NaN     NaN     NaN   
2017-05-09        NaN   NaN      NaN     NaN     NaN     NaN     NaN   

              成交量(股)    成交金额(元)  涨跌(元)  涨跌幅(%)    均价(元)  换手率(%)     A股流通市值(元)  \
日期                                                                              
2017-05-03  43568576  638781010  -0.06 -0.4021  14.6615  0.2015  3.212476e+11   
2017-05-04  19225492  283864640  -0.10 -0.6729   14.765  0.0889  3.190858e+11   
2017-05-05       NaN        NaN    NaN     NaN      NaN     NaN           NaN   
2017-05-08       NaN        NaN    NaN     NaN      NaN     NaN           NaN   
2017-05-09       NaN        NaN    NaN     NaN      NaN     NaN           NaN   

                  总市值(元)     A股流通股本(股)     市盈率  
日期                                              
2017-05-03  3.212476e+11  2.161828e+10  6.0500  
2017-05-04  3.190858e+11  2.161828e+10  6.0093  
2017-05-05           NaN           NaN     NaN  
2017-05-08           NaN           NaN     NaN  
2017-05-09           NaN           NaN     NaN

In [25]:
data['开盘价(元)'].expanding(min_periods=1).mean()

日期
2016-01-04    16.144400
2016-01-05    15.804400
2016-01-06    15.805867
2016-01-07    15.784525
2016-01-08    15.761120
                ...    
2017-05-03    16.041489
2017-05-04    16.038314
2017-05-05    16.034769
2017-05-08    16.030695
2017-05-09    16.026356
Name: 开盘价(元), Length: 309, dtype: float64

In [27]:
data['expanding Open mean'] = data['开盘价(元)'].expanding(min_periods=1).mean()
data[['开盘价(元)', 'expanding Open mean']].plot(figsize=(16,6))

<AxesSubplot:xlabel='日期'>

In [30]:
data['former 30 days rolling Close mean'] = data['收盘价(元)'].rolling(20).mean()
close_std = data['收盘价(元)'].rolling(20).std()
data['upper bound'] = data['former 30 days rolling Close mean'] + 2 * close_std
data['lower bound'] = data['former 30 days rolling Close mean'] - 2 * close_std

data[['收盘价(元)', 'former 30 days rolling Close mean', 'upper bound', 'lower bound']].plot(figsize=(16,6))

<AxesSubplot:xlabel='日期'>